AutoConnect: false
AutoConnectTimeOut: 10
ServerAddress: LocalHost
HideUIWhenConnected: true
HideCursorWhenConnected: true
VSyncCount: 1
MaxQueuedFrames: 0
FixedDeltaTime: 1000000
SyncFrameTimeOut: 2
