AutoConnect: true
AutoConnectTimeOut: 10
ServerAddress: 127.0.0.1
ServerPort: 8800
HideUIWhenConnected: true
HideCursorWhenConnected: true
VSyncCount: 1
MaxQueuedFrames: 2
FixedDeltaTime: 1000000
SyncFrameTimeOut: 2
FullScreenMode: FullScreenWindow
Version: 0
ExtendParam: {}
