AutoConnect: true
AutoConnectTimeOut: 10
ServerAddress: localhost
HideUIWhenConnected: true
HideCursorWhenConnected: true
VSyncCount: 1
MaxQueuedFrames: 2
FixedDeltaTime: 1000000
SyncFrameTimeOut: 2
FullScreenMode: FullScreenWindow
Version: 0
ExtendParam: {}
